# Generated by Django 5.0.4 on 2024-05-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetectionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_id", models.CharField(max_length=255)),
                ("confidence", models.FloatField()),
                ("x1", models.IntegerField()),
                ("y1", models.IntegerField()),
                ("x2", models.IntegerField()),
                ("y2", models.IntegerField()),
                ("image_path", models.CharField(max_length=255)),
                ("result_path", models.CharField(max_length=255)),
            ],
        ),
    ]
