# Generated by Django 5.0.6 on 2024-05-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0002_detectionresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="detectionresult",
            name="image",
            field=models.ImageField(default=1, upload_to="images/"),
            preserve_default=False,
        ),
    ]
